import { ColorProvider } from "@/providers/ColorProvider";

import type { Metadata } from "next";
import '@fontsource-variable/onest';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ColorProvider>
        <body className="overflow-hidden w-screen h-screen">
          {children}
        </body>
      </ColorProvider>
    </html>
  );
}
